apiVersion: v1
kind: Pod
metadata:
  name: coreutils-make-pod-n{pod_index}
  labels:
    workload: make
    testContext: foreground
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  schedulerName: "{scheduler_name}"
  containers:
  - name: make-container
    image: load-aware/coreutils:deps
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "for i in $(seq 1 50); do echo 'making' && make clean && make -j 4; done"]
    resources:
      requests:
        cpu: "100m"
  restartPolicy: Never
