---
# NFD Operator namespace name
nfd_operator_namespace: "openshift-nfd"

# NFD Operator CRD Statuses
nfd_operator_degraded_status: "Degraded"
nfd_operator_progressing_status: "Progressing"
nfd_operator_available_status: "Available"

# NFD Operator Resource retries and delays (in seconds)
nfd_operator_resource_retries: 10
nfd_operator_resource_delay: 20

# cluster-nfd-operator temporary repo
tmp_cluster_nfd_operator: "/tmp/__cluster-nfd-operator"

# Search keys
is_daemonset: "IS_DS"
is_role: "IS_ROLE"
is_rolebinding: "IS_RB"
is_clusterrole: "IS_CR"
is_clusterrolebinding: "IS_CLROB"
is_service: "IS_SVC"
is_serviceaccount: "IS_SA"
is_configmap: "IS_CM"
is_securitycontextconstraints: "IS_SCC"
