---
# If no ClusterRoles were found at all, then something is wrong.
- name: Search to see if the NFD Operator ClusterRoles exist
  fail: msg="No ClusterRoles were found"
  when: all_nfd_operator_manifests.results | selectattr(search_key,'contains',search_val) | list | count == 0
  vars:
    search_key: 'stdout'
    search_val: '{{ is_clusterrole }}'

# Get Role names
- name: Get the NFD Operator's ClusterRole names from the manifests
  shell: |
    cat '{{ clusterrole_manifest.manifest.path }}' | shyaml get-value metadata.name
  register: nfd_operator_clusterrole_names
  with_items: '{{ all_nfd_operator_manifests.results | selectattr(search_key,"contains",search_val) | list }}'
  loop_control:
    loop_var: clusterrole_manifest
    label: '{{ clusterrole_manifest.stdout_lines }}'
  vars:
    search_key: 'stdout'
    search_val: '{{ is_clusterrole }}'

# Attempt to retreive the roles from the cluster to see if they exist
- name: Attempt to retreive the NFD Operator ClusterRoles
  shell: oc get clusterrole '{{ clusterrole_name.stdout }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  retries: '{{ nfd_operator_resource_retries }}'
  delay: '{{ nfd_operator_resource_delay }}'
  register: nfd_operator_clusterroles_do_not_exist
  failed_when: false
  with_items: '{{ nfd_operator_clusterrole_names.results }}'
  loop_control:
    loop_var: clusterrole_name
    label: '{{ clusterrole_name.stdout }}'

- name: If any of the NFD Operator ClusterRoles do not exist, then we cannot continue
  fail: msg="All NFD Operator ClusterRoles must be initialized before running this role"
  when: clusterrole_status.stderr != ''
  with_items: "{{ nfd_operator_clusterroles_do_not_exist.results }}"
  loop_control:
    loop_var: clusterrole_status
    label: "{{ clusterrole_status.stdout }}"
