---
# If no DaemonSets were found at all, then something is wrong.
- name: Search to see if the NFD Operator DaemonSets exist
  fail: msg="One or more DaemonSets were not found"
  when: all_nfd_operator_manifests.results | selectattr(search_key,'contains',search_val) | list | count == 0
  vars:
    search_key: 'stdout'
    search_val: '{{ is_daemonset }}'

# Get DaemonSet names
- name: Get the NFD Operator's DaemonSet names from the manifests
  shell: |
    cat '{{ daemonset_manifest.manifest.path }}' | shyaml get-value metadata.name
  register: nfd_operator_daemonset_names
  with_items: '{{ all_nfd_operator_manifests.results | selectattr(search_key,"contains",search_val) | list }}'
  loop_control:
    loop_var: daemonset_manifest
    label: '{{ daemonset_manifest.stdout_lines }}'
  vars:
    search_key: 'stdout'
    search_val: '{{ is_daemonset }}'

- name: Attempt to retreive the NFD Operator DaemonSets
  shell: oc get ds '{{ daemonset_name.stdout }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  retries: '{{ nfd_operator_resource_retries }}'
  delay: '{{ nfd_operator_resource_delay }}'
  register: nfd_operator_dses_do_not_exist
  failed_when: false
  with_items: '{{ nfd_operator_daemonset_names.results }}'
  loop_control:
    loop_var: daemonset_name
    label: '{{ daemonset_name.stdout }}'

- name: If any of the NFD Operator DaemonSets do not exist, then we cannot continue
  fail: msg="All NFD Operator DaemonSets must be initialized before running this role"
  when: daemonset_status.stderr != ''
  with_items: "{{ nfd_operator_dses_do_not_exist.results }}"
  loop_control:
    loop_var: daemonset_status
    label: "{{ daemonset_status.stdout }}"
