---
# If no Roles were found at all, then something is wrong.
- name: Search to see if the NFD Operator Roles exist
  fail: msg="No Roles were found"
  when: all_nfd_operator_manifests.results | selectattr(search_key,'contains',search_val) | list | count == 0
  vars:
    search_key: 'stdout'
    search_val: '{{ is_role }}'

# Get Role names
- name: Get the NFD Operator's Role names from the manifests
  shell: |
    cat '{{ role_manifest.manifest.path }}' | shyaml get-value metadata.name
  register: nfd_operator_role_names
  with_items: '{{ all_nfd_operator_manifests.results | selectattr(search_key,"contains",search_val) | list }}'
  loop_control:
    loop_var: role_manifest
    label: '{{ role_manifest.stdout_lines }}'
  vars:
    search_key: 'stdout'
    search_val: '{{ is_role }}'

# Attempt to retreive the roles from the cluster to see if they exist
- name: Attempt to retreive the NFD Operator Roles
  shell: oc get role '{{ rrole_name.stdout }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  retries: '{{ nfd_operator_resource_retries }}'
  delay: '{{ nfd_operator_resource_delay }}'
  register: nfd_operator_roles_do_not_exist
  failed_when: false
  with_items: '{{ nfd_operator_role_names.results }}'
  loop_control:
    loop_var: rrole_name
    label: '{{ rrole_name.stdout }}'

- name: If any of the NFD Operator Roles do not exist, then we cannot continue
  fail: msg="All NFD Operator Roles must be initialized before running this role"
  when: rrole_status.stderr != ''
  with_items: "{{ nfd_operator_roles_do_not_exist.results }}"
  loop_control:
    loop_var: rrole_status
    label: "{{ rrole_status.stdout }}"
