---
# If the SecurityContextConstraints were not found at all, then something is wrong.
- name: Search to see if the NFD Operator SecurityContextConstraints exist
  fail: msg="No SecurityContextConstraints were found"
  when: all_nfd_operator_manifests.results | selectattr(search_key,'contains',search_val) | list | count == 0
  vars:
    search_key: 'stdout'
    search_val: '{{ is_securitycontextconstraints }}'

# Get SecurityContextConstraints names
- name: Get the NFD Operator's SecurityContextConstraints name from the manifests
  shell: |
    cat '{{ scc_manifest.manifest.path }}' | shyaml get-value metadata.name
  register: nfd_operator_scc_names
  with_items: '{{ all_nfd_operator_manifests.results | selectattr(search_key,"contains",search_val) | list }}'
  loop_control:
    loop_var: scc_manifest
    label: '{{ scc_manifest.stdout_lines }}'
  vars:
    search_key: 'stdout'
    search_val: '{{ is_securitycontextconstraints }}'

# Attempt to retreive the SecurityContextConstraints from the cluster to see if they exist
- name: Attempt to retreive the NFD Operator SecurityContextConstraints
  shell: oc get scc '{{ scc_name.stdout }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  retries: '{{ nfd_operator_resource_retries }}'
  delay: '{{ nfd_operator_resource_delay }}'
  register: nfd_operator_sccs_do_not_exist
  failed_when: false
  with_items: '{{ nfd_operator_scc_names.results }}'
  loop_control:
    loop_var: scc_name
    label: '{{ scc_name.stdout }}'

- name: If the NFD SecurityContextConstraints do not exist, then we cannot continue
  fail: msg="The NFD Operator SecurityContextConstraints must be initialized before running this role"
  when: scc_status.stderr != ''
  with_items: "{{ nfd_operator_sccs_do_not_exist.results }}"
  loop_control:
    loop_var: scc_status
    label: "{{ scc_status.stdout }}"
