---
# If no ServiceAccounts were found at all, then something is wrong.
- name: Search to see if the NFD Operator ServiceAccounts exist
  fail: msg="No ServiceAccounts were found"
  when: all_nfd_operator_manifests.results | selectattr(search_key,'contains',search_val) | list | count == 0
  vars:
    search_key: 'stdout'
    search_val: '{{ is_serviceaccount }}'

# Get ServiceAccount names
- name: Get the NFD Operator's ServiceAccount names from the manifests
  shell: |
    cat '{{ serviceaccount_manifest.manifest.path }}' | shyaml get-value metadata.name
  register: nfd_operator_serviceaccount_names
  with_items: '{{ all_nfd_operator_manifests.results | selectattr(search_key,"contains",search_val) | list }}'
  loop_control:
    loop_var: serviceaccount_manifest
    label: '{{ serviceaccount_manifest.stdout_lines }}'
  vars:
    search_key: 'stdout'
    search_val: '{{ is_serviceaccount }}'

# Attempt to retreive the ServiceAccounts from the cluster to see if they exist
- name: Attempt to retreive the NFD Operator ServiceAccounts
  shell: oc get serviceaccount '{{ serviceaccount_name.stdout }}' -n '{{ nfd_operator_namespace }}' -oname | grep 'error'
  retries: '{{ nfd_operator_resource_retries }}'
  delay: '{{ nfd_operator_resource_delay }}'
  register: nfd_operator_serviceaccounts_do_not_exist
  failed_when: false
  with_items: '{{ nfd_operator_serviceaccount_names.results }}'
  loop_control:
    loop_var: serviceaccount_name
    label: '{{ serviceaccount_name.stdout }}'

- name: If any of the NFD Operator ServiceAccounts do not exist, then we cannot continue
  fail: msg="All NFD Operator ServiceAccounts must be initialized before running this role"
  when: serviceaccount_status.stderr != ''
  with_items: "{{ nfd_operator_serviceaccounts_do_not_exist.results }}"
  loop_control:
    loop_var: serviceaccount_status
    label: "{{ serviceaccount_status.stdout }}"
